-- MySQL dump 10.13  Distrib 8.0.34, for Win64 (x86_64)
--
-- Host: localhost    Database: financial_performance
-- ------------------------------------------------------
-- Server version	8.0.35

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!50503 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `data_dictionary`
--

DROP TABLE IF EXISTS `data_dictionary`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `data_dictionary` (
  `table_name` varchar(255) DEFAULT NULL,
  `column_name` varchar(255) DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `data_type` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `data_dictionary`
--

LOCK TABLES `data_dictionary` WRITE;
/*!40000 ALTER TABLE `data_dictionary` DISABLE KEYS */;
INSERT INTO `data_dictionary` VALUES ('banks','Bank_name','The name of the bank','varchar(255)'),('banks','Year_Of_Establishment','The year in which the bank was established','varchar(255)'),('banks','Location','The location of the bank','varchar(255)'),('banks','Telephone','The telephone number of the bank','varchar(200)'),('banks_asset','bank_name','The name of the bank','varchar(155)'),('banks_asset','year','The year of the financial data','year'),('banks_asset','cash_on_hand','The actual cash available to the bank for immediate withdrawal by customers or for conducting various banking activities','decimal(18,2)'),('banks_asset','cash_at_bank','The funds held by a bank in its accounts with other financial institutions','decimal(18,2)'),('banks_asset','reserve_nbe','The reserve amount with the National Bank of Ethiopia','decimal(18,2)'),('banks_asset','cash_foreign_banks','The amount of cash with foreign banks','decimal(18,2)'),('banks_asset','treasury_bills','The amount invested in treasury bills','decimal(18,2)'),('banks_asset','other_investments','The amount invested in other instruments','decimal(18,2)'),('banks_asset','non_curr_asset_sale','The amount from the sale of non-current assets','decimal(18,2)'),('banks_asset','sundry_debtors','The amounts owed to a bank by its customers for the sale of goods or services on credit','decimal(18,2)'),('banks_asset','prov_doubtful_debts','An estimated amount set aside by a bank to cover potential losses from customers who may not be able to pay their  debts.','decimal(18,2)'),('banks_asset','cust_lia_lc','The customer liabilities in the form of letter of credit','decimal(18,2)'),('banks_deposits','bank_name','The name of the bank','varchar(255)'),('banks_deposits','Year','The year for which the deposit data is recorded','year'),('banks_deposits','demand_deposit','The amount of demand deposits (current/checking deposits) in the bank','decimal(18,2)'),('banks_deposits','saving_deposit','The amount of saving deposits in the bank','decimal(18,2)'),('banks_deposits','fixed_deposit','The amount of fixed deposits (time deposits) in the bank','decimal(18,2)'),('banks_deposits','foreign_bank_ac','The amount of foreign bank accounts held by the bank','decimal(18,2)'),('capital_and_reserves','bank_name','The name of the bank.','varchar(155)'),('capital_and_reserves','year','The year in which the capital and reserves data is recorded.','year'),('capital_and_reserves','authorized_and_paid','The total amount of capital that has been authorized and paid up by the bank.','decimal(12,2)'),('capital_and_reserves','legal_reserves','The portion of the bank\'s reserves that is legally required to be set aside.','decimal(12,2)'),('capital_and_reserves','general_and_special_reserves','The reserves maintained by the bank for general and special purposes, such as covering potential losses or funding specific projects.','decimal(12,2)'),('capital_and_reserves','statutory_reserve','The portion of the bank\'s profits that is set aside as per statutory requirements or regulations.','decimal(12,2)'),('capital_and_reserves','retined_earning','The portion of the bank\'s earnings that is retained for future use and not distributed to shareholders as dividends.','decimal(12,2)'),('capital_and_reserves','profit_and_loss','The net profit or loss generated by the bank during a specific period.','decimal(12,2)'),('income_statement','bank_name','The name of the bank.','varchar(155)'),('income_statement','Year','The year for which the income statement data is recorded.','year'),('income_statement','interest_income','The total income generated by the bank from interest on loans, investments, and other interest-earning assets.','decimal(18,2)'),('income_statement','interest_expense','The total interest expense incurred by the bank on deposits, borrowings, and other interest-bearing liabilities.','decimal(18,2)'),('income_statement','service_charge_commission_income','The income earned by the bank from service charges and commissions, such as account maintenance fees or transaction fees.','decimal(18,2)'),('income_statement','gain_loss_foreign_currency_transactions','The gains or losses realized by the bank from foreign currency transactions, including exchange rate fluctuations.','decimal(18,2)'),('income_statement','gain_loss_equity_investment_associates','The gains or losses derived from the bank\'s equity investments in other companies or associates.','decimal(18,2)'),('income_statement','other_income','Any additional income sources not specifically mentioned above.','decimal(18,2)'),('income_statement','employees_salary_benefits','The total expenses related to employees\' salaries, wages, and benefits.','decimal(18,2)'),('income_statement','provision_doubtful_loans_other_assets','The amount set aside by the bank to cover potential losses from doubtful loans and other assets.','decimal(18,2)'),('income_statement','general_expenses','The general operating expenses incurred by the bank, such as rent, utilities, and marketing costs.','decimal(18,2)'),('income_statement','prior_year_adjustment','Any adjustments made to the income statement for prior years, if applicable.','decimal(18,2)'),('income_statement','operating_income_before_tax','The bank\'s operating income before accounting for taxes.','decimal(18,2)'),('income_statement','tax','The taxes levied on the bank\'s income, including income tax and other applicable taxes.','decimal(18,2)'),('loans','bank_name','The name of the bank.','varchar(255)'),('loans','Year','The year for which the loan data is recorded.','year'),('loans','short_term_loans','The total amount of loans provided by the bank with a short-term repayment period.','decimal(12,2)'),('loans','other_credit_balances','The outstanding balances of other forms of credit extended by the bank, such as lines of credit or revolving credit facilities.','decimal(12,2)'),('loans','margin_held_on_lc','The margin or collateral held by the bank against letters of credit (LC) issued.','decimal(12,2)'),('loans','long_term_loans','The total amount of loans provided by the bank with a long-term repayment period.','decimal(12,2)'),('loans','provision_for_taxation','The amount set aside by the bank to cover its tax obligations.','decimal(12,2)'),('loans','state_dividened_payable','The dividends payable by the bank to the state or government, if applicable.','decimal(12,2)'),('loans','other_provisions','Any other provisions made by the bank to cover potential losses or liabilities.','decimal(12,2)'),('loans','banks_liability_to_lc','The bank\'s liability or obligation arising from letters of credit (LC) received.','decimal(12,2)');
/*!40000 ALTER TABLE `data_dictionary` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2024-01-22 12:11:02
